// src2/src/app/cabecalho/cabecalho.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cabecalho',
  templateUrl: './cabecalho.component.html',
  styleUrls: ['./cabecalho.component.css']
})
export class CabecalhoComponent implements OnInit {

  constructor() {}

  ngOnInit(): void {
  }

}

<div>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#home">
                <img src="../../assets/icon/logo_cabecalho.png" alt="Logotipo Microben" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basic-navbar-nav" aria-controls="basic-navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basic-navbar-nav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#quemsomos">A microben</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#servicos_icons">Serviços</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#contato">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>

// src/src/components/Cabecalho.tsx
import styles from '../styles/Cabecalho.module.css'
import Image from 'next/image'
import logoCabecalho from '../../public/img/logo_cabecalho.png'

export default function Cabecalho() {
    return (
        <div>
            <nav className="navbar navbar-expand-lg bg-light">
                <div className="container-fluid">
                    <a className="navbar-brand" href="#home">
                        <Image src={logoCabecalho} alt="Logotipo Microben" />
                    </a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basic-navbar-nav" aria-controls="basic-navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="basic-navbar-nav">
                        <ul className="navbar-nav">
                            <li className="nav-item"><a className="nav-link" aria-current="page" href="#quemsomos" >A microben</a></li>
                            <li className="nav-item"><a className="nav-link" aria-current="page" >Serviços</a></li>
                            <li className="nav-item"><a className="nav-link" aria-current="page" href="#contato">Contato</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    )
}
