// with-static-export-app/components/Cabecalho.jsx
import styles from '../styles/Cabecalho.module.css'
import { Nav, Navbar, Container } from 'react-bootstrap'
import Image from 'next/image'
import logoCabecalho from '../public/img/logo_cabecalho.png'

export default function Cabecalho() {
    return (
        <div>
            <Navbar bg="light" expand="lg">
                <Container>
                    <Navbar.Brand href="#home">
                        <Image src={logoCabecalho} alt="Logotipo Microben" />
                    </Navbar.Brand>
                    <Navbar.Toggle aria-controls="basic-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                        <Nav className="me-auto">
                            <Nav.Link href="#quemsomos">A microben</Nav.Link>
                            <Nav.Link href="#servicos_icons">Serviços</Nav.Link>
                            <Nav.Link href="#contato">Contato</Nav.Link>
                        </Nav>
                    </Navbar.Collapse>
                </Container>
            </Navbar>
        </div>
    )
}

// src2/src/app/cabecalho/cabecalho.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cabecalho',
  templateUrl: './cabecalho.component.html',
  styleUrls: ['./cabecalho.component.css']
})
export class CabecalhoComponent implements OnInit {

  constructor() {}

  ngOnInit(): void {
  }

}

<div>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#home">
                <img src="../../assets/icon/logo_cabecalho.png" alt="Logotipo Microben" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basic-navbar-nav" aria-controls="basic-navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basic-navbar-nav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#quemsomos">A microben</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#servicos_icons">Serviços</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#contato">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
