// src/src/components/Contato.jsx
import { useState } from 'react'

export default function Contato() {
    const [nome, setNome] = useState('')
    const [email, setEmail] = useState('')
    const [mensagem, setMensagem] = useState('')
    const [submitted, setSubmitted] = useState(false)

    function reset() {
        console.log('Response succeeded!')
        setSubmitted(true)
        setNome('')
        setEmail('')
        setMensagem('')
    }

    const handleSubmit = (e) => {
        e.preventDefault()
        console.log('Sending')
        let data = {
            nome,
            email,
            mensagem
        }
        fetch('/api/contact', {
            method: 'POST',
            headers: {
                'Accept': 'application/json, text/plain, */*',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then((res) => {
            console.log('Response received')
            if (res.status === 200) {
                reset()
            }
        })
    }

    return (
        < div >
            <h4 className="text-danger text-center" id="contato">CONTATO</h4>
            <h3 className="text-center">Mande uma mensagem</h3>
            <div id="contato" className="row justify-content-md-center">
                <div className="col col-lg-4">
                    <form>
                        <div className="input-group mb-3" >
                            <span className="input-group-text">Nome</span>
                            <input type="text" className='form-control' minLength={3} name='nome' value={nome} onChange={(e) => { setNome(e.target.value) }} placeholder="Seu Nome" required />
                        </div>
                        <div className="input-group mb-3" >
                            <span className="input-group-text">e-Mail</span>
                            <input type="email" className='form-control' name='email' value={email} onChange={(e) => { setEmail(e.target.value) }} placeholder="Seu e-Mail" required />
                            <p>
                                Nunca compartilharemos seu e-mail com mais ninguém.
                            </p>
                        </div>
                        <div className="input-group mb-3" >
                            <span className="input-group-text">Mensagem</span>
                            <textarea className='form-control' rows={3} value={mensagem} onChange={(e) => { setMensagem(e.target.value) }} as="textarea" />
                        </div>
                        <button onClick={(e) => { handleSubmit(e) }} className="mb-3" variant="primary" type="submit">
                            Enviar
                        </button>
                        {/* <button className="mb-3 primary" type="submit">
                            Enviar
                        </button> */}
                    </form>
                </div>
            </div>
        </div >
    )
}

// src2/src/app/contato/contato.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-contato',
  templateUrl: './contato.component.html',
  styleUrls: ['./contato.component.css']
})
export class ContatoComponent implements OnInit {

  formulario!: FormGroup

  minhaMensagem = { nome: '', email: '', mensagem: '' };

  constructor() { }

  ngOnInit(): void {
    this.formulario = new FormGroup({
      inputNome: new FormControl(this.minhaMensagem.nome, Validators.required ),
      inputEmail: new FormControl(this.minhaMensagem.email, Validators.required ),
      inputMensagem: new FormControl(this.minhaMensagem.mensagem, [ Validators.required, Validators.minLength(5) ])
    })
  }

  public enviarMensagem(): void {
    console.log(this.formulario)
  }

  get nome() { return this.formulario.get('inputNome')!; }

  get email() { return this.formulario.get('inputEmail')!; }

  get mensagem() { return this.formulario.get('inputMensagem')!; }

}

<div>
    <h4 class="text-danger text-center" id="contato">CONTATO</h4>
    <h3 class="text-center">Mande uma mensagem</h3>
    <div id="contato" class="row justify-content-md-center">
        <div class="col col-lg-4">
            <form  [formGroup]="formulario" novalidate (ngSubmit)="enviarMensagem()">
                <div class="form-row">
                    <div class="form-group">
                        <input name='nome' type="text" placeholder="Seu Nome" class="form-control" formControlName="inputNome" required/>
                        <small *ngIf="nome.valid && (nome.dirty || nome.touched)" class="form-text text-success">Ok</small>
                        <small *ngIf="nome.invalid && (nome.dirty || nome.touched)" class="form-text text-danger">Nome Inválido</small>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <input name='email' type="email" placeholder="Seu e-Mail" class="form-control" formControlName="inputEmail" />
                        <small *ngIf="email.valid && (email.dirty || email.touched)" class="form-text text-success">Ok</small>
                        <small *ngIf="email.invalid && (email.dirty || email.touched)" class="form-text text-danger">e-Mail Inválido</small>
                    </div>
                </div>
                <p class="text-muted">
                    Nunca compartilharemos seu e-mail com mais ninguém.
                </p>
                <div class="form-row">
                    <div class="form-group">
                        <textarea name="mensagem" rows="5" cols="60" placeholder="Sua Mensagem" class="form-control" formControlName="inputMensagem" ></textarea>
                        <small *ngIf="mensagem.valid && (mensagem.dirty || mensagem.touched)" class="form-text text-success">Ok</small>
                        <small *ngIf="mensagem.invalid && (mensagem.dirty || mensagem.touched)" class="form-text text-danger">Mensagem Inválida</small>
                    </div>
                </div>
                <Button class="btn btn-primary btn-lg mb-3" type="submit">
                    Enviar
                </Button>
            </form>
        </div>
    </div>
</div>
